from build.building import *

BLE_PROFILE_SRCS = [
    'om_ancs/ancs_client.c',
    'om_bms/om_bms.c',
    'om_bms/service_om_bms.c',
    'om_cgms/om_cgms.c',
    'om_cgms/service_om_cgms.c',
    'om_dfu/om_dfu.c',
    'om_dfu/om_dfu_nvds.c',
    'om_dfu/om_dfu_ver_check.c',
    'om_dfu/service_om_dfu.c',
    'om_gap_dis_batt/service_common.c',
    'om_hid_media/app_hid_media.c',
    'om_tspp/service_tspp.c',
    'om_wechat_lite/app_wechat_lite.c',
]

BLE_PROFILE_INCS = [
    'om_ancs',
    'om_bms',
    'om_cgms',
    'om_dfu',
    'om_gap_dis_batt',
    'om_hid_media',
    'om_tspp',
    'om_wechat_lite',
]

group = DefineGroup(name='profile', srcs=BLE_PROFILE_SRCS, incs=BLE_PROFILE_INCS)

Return('group')
