ifeq ($(CONFIG_BLE), y)
BLE_DIR  = $(COMPONENTS_DIR)/ble

# ble common
ifeq ($(CONFIG_BLE_CONTROLLER), y)
COMPONENTS_INCS += $(BLE_DIR)/include
COMPONENTS_SRCS += $(BLE_DIR)/common/ob_mem_heap.c
endif

# controller
ifeq ($(CONFIG_BLE_CONTROLLER), y)
-include $(BLE_DIR)/controller/controller.mk
COMPONENTS_SRCS += $(BLE_CONTROLLER_SRCS)
COMPONENTS_INCS += $(BLE_CONTROLLER_INCS)
COMPONENTS_LIBS += $(BLE_CONTROLLER_LIBS)
COMPONENTS_DEFS += $(BLE_CONTROLLER_DEFS)
endif

# host
ifeq ($(CONFIG_BLE_HOST), y)
-include $(BLE_DIR)/host/host.mk
-include $(BLE_DIR)/profile/profile.mk
COMPONENTS_SRCS += $(BLE_HOST_SRCS)
COMPONENTS_INCS += $(BLE_HOST_INCS)
COMPONENTS_LIBS += $(BLE_HOST_LIBS)
COMPONENTS_DEFS += $(BLE_HOST_DEFS)
endif

ifeq ($(CONFIG_BLE_PROFILE), y)
-include $(BLE_DIR)/profile/profile.mk
COMPONENTS_SRCS += $(BLE_PROFILE_SRCS)
COMPONENTS_INCS += $(BLE_PROFILE_INCS)
COMPONENTS_LIBS += $(BLE_PROFILE_LIBS)
COMPONENTS_DEFS += $(BLE_PROFILE_DEFS)
endif

# mesh
ifeq ($(CONFIG_BLE_MESH), y)
-include $(BLE_DIR)/mesh/mesh.mk
COMPONENTS_SRCS += $(BLE_MESH_SRCS)
COMPONENTS_INCS += $(BLE_MESH_INCS)
COMPONENTS_LIBS += $(BLE_MESH_LIBS)
COMPONENTS_DEFS += $(BLE_MESH_DEFS)
endif

endif
