from build.building import *


PROJECT_MAIN_SRCS = [
                    'main.c',
                    'app_om24g.c',
                    'system.c',
                    ]

group = DefineGroup(name='main', srcs=PROJECT_MAIN_SRCS, incs=None)

Return('group')
