#define CONFIG_TOOL_CHAIN_OPTIMIZATION_LEVEL 4
#define CONFIG_BOARD_EVB 1
#define CONFIG_GLCD_GC9C01 1
#define CONFIG_NVDS 1
#define CONFIG_NON_RTOS 1
#define CONFIG_XIP_FLASH 1
#define CONFIG_OM_ASSERT 1
#define CONFIG_MEM_NUM 1
