from build.building import *

group=[]
if GetDepend('CONFIG_CHERRYUSB'):
    incs =  ['.']
    incs += ['common']
    incs += ['core']
    incs += ['class/cdc']
    incs += ['class/msc']
    incs += ['class/hid']
    incs += ['class/audio']
    incs += ['class/video']
    incs += ['class/wireless']
    incs += ['class/dfu']
    incs += ['class/midi']
    incs += ['class/vendor/net']
    incs += ['class/vendor/serial']
    srcs = []

    # USB DEVICE
    if GetDepend('CONFIG_CHERRYUSB_DEVICE'):
        srcs += ['core/usbd_core.c']

        if GetDepend('CONFIG_CHERRYUSB_OSAL_FREERTOS'):
            srcs += ['osal/usb_osal_freertos.c']

        if GetDepend('CONFIG_CHERRYUSB_DEVICE_MUSB_OM'):
            srcs += ['port/musb/usb_dc_musb.c']
            srcs += ['port/musb/usb_glue_om.c']

        if GetDepend('CONFIG_CHERRYUSB_DEVICE_CDC_ACM'):
            srcs += ['class/cdc/usbd_cdc_acm.c']
        if GetDepend('CONFIG_CHERRYUSB_DEVICE_HID'):
            srcs += ['class/hid/usbd_hid.c']
        if GetDepend('CONFIG_CHERRYUSB_DEVICE_MSC'):
            srcs += ['class/msc/usbd_msc.c']
        if GetDepend('CONFIG_CHERRYUSB_DEVICE_AUDIO'):
            srcs += ['class/audio/usbd_audio.c']
        if GetDepend('CONFIG_CHERRYUSB_DEVICE_VIDEO'):
            srcs += ['class/video/usbd_video.c']
        if GetDepend('CONFIG_CHERRYUSB_DEVICE_CDC_RNDIS'):
            srcs += ['class/wireless/usbd_rndis.c']
        if GetDepend('CONFIG_CHERRYUSB_DEVICE_CDC_ECM'):
            srcs += ['class/cdc/usbd_cdc_ecm.c']
        if GetDepend('CONFIG_CHERRYUSB_DEVICE_CDC_NCM'):
            srcs += ['class/cdc/usbd_cdc_ncm.c']
        if GetDepend('CONFIG_CHERRYUSB_USING_DFU'):
            srcs += ['class/dfu/usbd_dfu.c']

    # USB HOST
    if GetDepend('CONFIG_CHERRYUSB_HOST'):
        srcs += ['core/usbh_core.c']
        srcs += ['class/hub/usbh_hub.c']

        if GetDepend('CONFIG_CHERRYUSB_HOST_MUSB_ES'):
            srcs += ['port/musb/usb_hc_musb.c']
            srcs += ['port/musb/usb_glue_es.c']

        if GetDepend('CONFIG_CHERRYUSB_HOST_CDC_ACM'):
            srcs += ['class/cdc/usbh_cdc_acm.c']
        if GetDepend('CONFIG_CHERRYUSB_HOST_HID'):
            srcs += ['class/hid/usbh_hid.c']
        if GetDepend('CONFIG_CHERRYUSB_HOST_MSC'):
            srcs += ['class/msc/usbh_msc.c']
        if GetDepend('CONFIG_CHERRYUSB_HOST_CDC_RNDIS'):
            srcs += ['class/wireless/usbh_rndis.c']
        if GetDepend('CONFIG_CHERRYUSB_HOST_CDC_ECM'):
            srcs += ['class/cdc/usbh_cdc_ecm.c']
        if GetDepend('CONFIG_CHERRYUSB_HOST_CDC_NCM'):
            srcs += ['class/cdc/usbh_cdc_ncm.c']
        if GetDepend('CONFIG_CHERRYUSB_HOST_VIDEO'):
            srcs += ['class/video/usbh_video.c']
        if GetDepend('CONFIG_CHERRYUSB_HOST_AUDIO'):
            srcs += ['class/audio/usbh_audio.c']
        if GetDepend('CONFIG_CHERRYUSB_HOST_BLUETOOTH'):
            srcs += ['class/wireless/usbh_bluetooth.c']
        if GetDepend('CONFIG_CHERRYUSB_HOST_ASIX'):
            srcs += ['class/vendor/net/usbh_asix.c']
        if GetDepend('CONFIG_CHERRYUSB_HOST_RTL8152'):
            srcs += ['class/vendor/net/usbh_rtl8152.c']
        if GetDepend('CONFIG_CHERRYUSB_HOST_FTDI'):
            srcs += ['class/vendor/serial/usbh_ftdi.c']
        if GetDepend('CONFIG_CHERRYUSB_HOST_CH34X'):
            srcs += ['class/vendor/serial/usbh_ch34x.c']
        if GetDepend('CONFIG_CHERRYUSB_HOST_CP210X'):
            srcs += ['class/vendor/serial/usbh_cp210x.c']
        if GetDepend('CONFIG_CHERRYUSB_HOST_PL2303'):
            srcs += ['class/vendor/serial/usbh_pl2303.c']

    group = DefineGroup(name='CherryUSB', srcs=srcs, incs=incs)

Return('group')
