from build.building import *

PROJECT_EXAMPLE_INCS = ['.']
PROJECT_EXAMPLE_SRCS = ['example_aes.c']
PROJECT_EXAMPLE_SRCS += ['example_audio.c']
PROJECT_EXAMPLE_SRCS += ['example_efuse.c']
PROJECT_EXAMPLE_SRCS += ['example_flash.c']
PROJECT_EXAMPLE_SRCS += ['example_gpadc.c']
PROJECT_EXAMPLE_SRCS += ['example_gpdma.c']
PROJECT_EXAMPLE_SRCS += ['example_gpio.c']
PROJECT_EXAMPLE_SRCS += ['example_i2c.c']
PROJECT_EXAMPLE_SRCS += ['example_i2s.c']
PROJECT_EXAMPLE_SRCS += ['example_ir.c']
PROJECT_EXAMPLE_SRCS += ['example_lcd.c']
PROJECT_EXAMPLE_SRCS += ['example_lptimer.c']
PROJECT_EXAMPLE_SRCS += ['example_pmu_timer.c']
PROJECT_EXAMPLE_SRCS += ['example_qdec.c']
PROJECT_EXAMPLE_SRCS += ['example_rgb.c']
PROJECT_EXAMPLE_SRCS += ['example_rtc.c']
PROJECT_EXAMPLE_SRCS += ['example_spi.c']
PROJECT_EXAMPLE_SRCS += ['example_timer.c']
PROJECT_EXAMPLE_SRCS += ['example_uart.c']
PROJECT_EXAMPLE_SRCS += ['example_wdt.c']
PROJECT_EXAMPLE_SRCS += ['example_shelf_mode.c']

group = DefineGroup(name='drv_example', srcs=PROJECT_EXAMPLE_SRCS, incs=PROJECT_EXAMPLE_INCS)

Return('group')
