SEGGER_RTT_DIR = $(COMPONENTS_DIR)/segger_rtt

ifeq ($(CONFIG_SEGGER_RTT), y)
COMPONENTS_INCS += $(SEGGER_RTT_DIR)
COMPONENTS_SRCS += $(SEGGER_RTT_DIR)/SEGGER_RTT.c
COMPONENTS_SRCS += $(SEGGER_RTT_DIR)/SEGGER_RTT_printf.c
endif