MANU_CALIB_BLE_V2_DIR = $(MANU_SYSTEM_DIR)/manu_calib_ble_v2

MANU_CALIB_BLE_V2_DEFS =
MANU_CALIB_BLE_V2_INCS = $(MANU_CALIB_BLE_V2_DIR)
MANU_CALIB_BLE_V2_SRCS = $(MANU_CALIB_BLE_V2_DIR)/manu_calib_ble_v2.c