from build.building import *


BLE_MESH_SRCS = []

BLE_MESH_INCS = ['include']

BLE_MESH_DEFS = []

BLE_MESH_LIBS = []

# Append library
if GetDepend('CONFIG_TOOL_CHAIN_GCC'):
        BLE_MESH_LIBS += ['lib/GCC/libblemesh.a']
elif GetDepend('CONFIG_TOOL_CHAIN_ARMCLANG'):
        BLE_MESH_LIBS += ['lib/ARM/libblemesh.lib']
elif GetDepend('CONFIG_TOOL_CHAIN_ICCARM'):
        BLE_MESH_LIBS += ['lib/IAR/libblemesh.a']

group = DefineGroup(name='mesh', srcs=BLE_MESH_SRCS, incs=BLE_MESH_INCS, libs=BLE_MESH_LIBS, CPPDEFINES=BLE_MESH_DEFS)

Return('group')