
BLE_CONTROLLER_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

BLE_CONTROLLER_SRCS =

BLE_CONTROLLER_INCS = $(BLE_CONTROLLER_DIR)include

BLE_CONTROLLER_LIBS =

BLE_CONTROLLER_DEFS =

ifeq ($(CONFIG_BLE_CONTROLLER_LIB_1PERIPHERAL), y)
BLE_CONTROLLER_LIBS += $(BLE_CONTROLLER_DIR)lib/GCC/libblectlr_1peripheral.a
BLE_CONTROLLER_DEFS += \
	CONFIG_LE_BROADCASTER=1 \
	CONFIG_LE_PERIPHERAL=1 \
	CONFIG_LE_ACTIVITY_NB=2 \
	CONFIG_LE_CONNECTION_NB=1 \
	CONFIG_LE_WHITELIST_NB=6 \
	CONFIG_LE_LL_HCI_CMD_PKTS_NB=2 \
	CONFIG_LE_LL_RX_DATA_BUF_NB=3 \
	CONFIG_LE_LL_RX_DATA_BUF_SIZE=256 \
	CONFIG_LE_LL_TX_ACL_BUF_NB=3 \
	CONFIG_LE_LL_TX_ACL_BUF_SIZE=256 \
	CONFIG_LE_LL_TX_ADV_BUF_NB=2 \
	CONFIG_LE_LL_TX_ADV_FRAG_NB=1 \
	CONFIG_LE_LL_TX_ADV_FRAG_BUF_SIZE=37 \
	CONFIG_LE_LL_TX_LLCP_BUF_NB=3 \

else ifeq ($(CONFIG_BLE_CONTROLLER_LIB_FULL), y)
BLE_CONTROLLER_LIBS += $(BLE_CONTROLLER_DIR)lib/GCC/libblectlr_full.a
BLE_CONTROLLER_DEFS += \
	CONFIG_LE_BROADCASTER=1 \
	CONFIG_LE_OBSERVER=1 \
	CONFIG_LE_PERIPHERAL=1 \
	CONFIG_LE_CENTRAL=1 \
	CONFIG_LE_ACTIVITY_NB=10 \
	CONFIG_LE_CONNECTION_NB=8 \
	CONFIG_LE_WHITELIST_NB=6 \
	CONFIG_LE_LL_HCI_CMD_PKTS_NB=2 \
	CONFIG_LE_LL_RX_DATA_BUF_NB=3 \
	CONFIG_LE_LL_RX_DATA_BUF_SIZE=256 \
	CONFIG_LE_LL_TX_ACL_BUF_NB=3 \
	CONFIG_LE_LL_TX_ACL_BUF_SIZE=256 \
	CONFIG_LE_LL_TX_ADV_BUF_NB=5 \
	CONFIG_LE_LL_TX_ADV_FRAG_NB=2 \
	CONFIG_LE_LL_TX_ADV_FRAG_BUF_SIZE=254 \
	CONFIG_LE_LL_TX_LLCP_BUF_NB=11 \

else ifeq ($(CONFIG_BLE_CONTROLLER_LIB_FULL_PLUS), y)
BLE_CONTROLLER_LIBS += $(BLE_CONTROLLER_DIR)lib/GCC/libblectlr_full_plus.a
BLE_CONTROLLER_DEFS += \
	CONFIG_LE_BROADCASTER=1 \
	CONFIG_LE_OBSERVER=1 \
	CONFIG_LE_PERIPHERAL=1 \
	CONFIG_LE_CENTRAL=1 \
	CONFIG_LE_ACTIVITY_NB=22 \
	CONFIG_LE_CONNECTION_NB=20 \
	CONFIG_LE_WHITELIST_NB=6 \
	CONFIG_LE_LL_HCI_CMD_PKTS_NB=2 \
	CONFIG_LE_LL_RX_DATA_BUF_NB=3 \
	CONFIG_LE_LL_RX_DATA_BUF_SIZE=256 \
	CONFIG_LE_LL_TX_ACL_BUF_NB=3 \
	CONFIG_LE_LL_TX_ACL_BUF_SIZE=256 \
	CONFIG_LE_LL_TX_ADV_BUF_NB=5 \
	CONFIG_LE_LL_TX_ADV_FRAG_NB=2 \
	CONFIG_LE_LL_TX_ADV_FRAG_BUF_SIZE=254 \
	CONFIG_LE_LL_TX_LLCP_BUF_NB=11 \

else ifeq ($(CONFIG_BLE_CONTROLLER_LIB_VELA_MESH), y)
BLE_CONTROLLER_LIBS += $(BLE_CONTROLLER_DIR)lib/GCC/libblectlr_vela_mesh.a
BLE_CONTROLLER_DEFS += \
	CONFIG_LE_BROADCASTER=1 \
	CONFIG_LE_OBSERVER=1 \
	CONFIG_LE_PERIPHERAL=1 \
	CONFIG_LE_CENTRAL=1 \
	CONFIG_LE_ACTIVITY_NB=8 \
	CONFIG_LE_CONNECTION_NB=2 \
	CONFIG_LE_WHITELIST_NB=6 \
	CONFIG_LE_LL_HCI_CMD_PKTS_NB=4 \
	CONFIG_LE_LL_RX_DATA_BUF_NB=3 \
	CONFIG_LE_LL_RX_DATA_BUF_SIZE=256 \
	CONFIG_LE_LL_TX_ACL_BUF_NB=4 \
	CONFIG_LE_LL_TX_ACL_BUF_SIZE=256 \
	CONFIG_LE_LL_TX_ADV_BUF_NB=8 \
	CONFIG_LE_LL_TX_ADV_FRAG_NB=1 \
	CONFIG_LE_LL_TX_ADV_FRAG_BUF_SIZE=254 \
	CONFIG_LE_LL_TX_LLCP_BUF_NB=5 \

endif
