/* ----------------------------------------------------------------------------
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 * -------------------------------------------------------------------------- */

/**
 * @defgroup PIN PIN
 * @ingroup  DRIVER
 * @brief    PIN driver
 * @details  PIN driver apis and typedefs header file
 *
 * @version
 * Version 1.0
 *  - Initial release
 *
 * @{
 */

#ifndef __DRV_PIN_H
#define __DRV_PIN_H


/*******************************************************************************
 * INCLUDES
 */
#include "RTE_driver.h"
#if (RTE_PIN)
#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif


/*******************************************************************************
 * TYPEDEFS
 */
/// Pinmux Configuration Defination
typedef enum {
    PINMUX_JTAG_MODE_CFG                = 0,
    PINMUX_DEBUG_MODE_CFG               = 1,
    PINMUX_I2C0_SCK_CFG                 = 2,
    PINMUX_I2C0_SDA_CFG                 = 3,
    PINMUX_UART0_TRX_CFG                = 4,
    PINMUX_UART0_RX_CFG                 = 5,
    PINMUX_I2C1_SCK_CFG                 = 6,
    PINMUX_I2C1_SDA_CFG                 = 7,
    PINMUX_OSPI1_SI_CFG                 = 8,
    PINMUX_OSPI1_SO_CFG                 = 9,
    PINMUX_OSPI1_HD_CFG                 = 10,
    PINMUX_OSPI1_WP_CFG                 = 11,
    PINMUX_OSPI1_CK_CFG                 = 12,
    PINMUX_OSPI1_CS_CFG                 = 13,
    PINMUX_INPUT_MODE_CFG               = 14,   // analog input for GPADC
    PINMUX_UART1_RX_CFG                 = 15,
    PINMUX_UART1_TRX_CFG                = 16,
    PINMUX_UART1_CTS_CFG                = 17,
    PINMUX_UART1_RTS_CFG                = 18,
    PINMUX_SPI0_DI_CFG                  = 19,
    PINMUX_SPI0_DIO_CFG                 = 20,
    PINMUX_SPI0_CS_CFG                  = 21,
    PINMUX_SPI0_SCK_CFG                 = 22,
    PINMUX_SPI1_DI_CFG                  = 23,
    PINMUX_SPI1_DIO_CFG                 = 24,
    PINMUX_SPI1_CS_CFG                  = 25,
    PINMUX_SPI1_SCK_CFG                 = 26,
    PINMUX_TX_EXT_PD_CFG                = 27,
    PINMUX_GPIO_MODE_CFG                = 28,
    PINMUX_RX_EXT_PD_CFG                = 29,
    PINMUX_PTA_ACTIVE_IN_CFG            = 30,
    PINMUX_PTA_ACTIVE_OUT_CFG           = 31,
    PINMUX_PTA_PRIORITY_CFG             = 32,
    PINMUX_PTA_FREQ_CFG                 = 33,
    PINMUX_TIM0_ETR_CFG                 = 34,
    PINMUX_TIM1_ETR_CFG                 = 35,
    PINMUX_TIM2_ETR_CFG                 = 36,
    PINMUX_TIM0_BKIN_CFG                = 37,
    PINMUX_TIM1_BKIN_CFG                = 38,
    PINMUX_TIM2_BKIN_CFG                = 39,
    PINMUX_TIM0_IO0_CFG                 = 40,
    PINMUX_TIM0_IO1_CFG                 = 41,
    PINMUX_TIM0_IO2_CFG                 = 42,
    PINMUX_TIM0_IO3_CFG                 = 43,
    PINMUX_TIM0_OUTN0_CFG               = 44,
    PINMUX_TIM0_OUTN1_CFG               = 45,
    PINMUX_TIM0_OUTN2_CFG               = 46,
    PINMUX_TIM1_OUT0_CFG                = 47,
    PINMUX_TIM1_OUT1_CFG                = 48,
    PINMUX_TIM1_OUT2_CFG                = 49,
    PINMUX_TIM1_OUT3_CFG                = 50,
    PINMUX_TIM1_OUTN0_CFG               = 51,
    PINMUX_TIM1_OUTN1_CFG               = 52,
    PINMUX_TIM1_OUTN2_CFG               = 53,
    PINMUX_TIM2_OUT0_CFG                = 54,
    PINMUX_TIM2_OUT1_CFG                = 55,
    PINMUX_TIM2_OUT2_CFG                = 56,
    PINMUX_TIM2_OUT3_CFG                = 57,
    PINMUX_TIM2_OUTN0_CFG               = 58,
    PINMUX_TIM2_OUTN1_CFG               = 59,
    PINMUX_TIM2_OUTN2_CFG               = 60,
    PINMUX_UART2_RX_CFG                 = 61,
    PINMUX_UART2_TRX_CFG                = 62,
    PINMUX_AUDIO_EXT_CLK_CFG            = 63,
    PINMUX_DMIC_IN_CFG                  = 64,
    PINMUX_DMIC_CLK_CFG                 = 65,
    PINMUX_I2S_SDI_CFG                  = 66,
    PINMUX_I2S_WS_CFG                   = 67,
    PINMUX_I2S_SCLK_CFG                 = 68,
    PINMUX_I2S_SDO_CFG                  = 69,
    PINMUX_IRTX_OUT_CFG                 = 70,
    PINMUX_RGB_OUT_CFG                  = 71,
    PINMUX_USB_DM_CFG                   = 72,
    PINMUX_USB_DP_CFG                   = 73,
    PINMUX_USB_OTG_CFG                  = 74,
    PINMUX_USB_OTG_VBUS_EN_CFG          = 75,
    PINMUX_OSPI1_CS1_CF                 = 76,
    PINMUX_LCD_SI_CFG                   = 77,
    PINMUX_LCD_SO_CFG                   = 78,
    PINMUX_LCD_HD_CFG                   = 79,
    PINMUX_LCD_WP_CFG                   = 80,
    PINMUX_LCD_CK_CFG                   = 81,
    PINMUX_LCD_CS0_CFG                  = 82,
    PINMUX_LCD_CS1_CFG                  = 83,
    PINMUX_QDEC_XA_CFG                  = 84,
    PINMUX_QDEC_XB_CFG                  = 85,
    PINMUX_QDEC_LED_CFG                 = 86,
    PINMUX_RF_SCK_CFG                   = 87,
    PINMUX_RF_SDO_CFG                   = 88,
    PINMUX_RF_CSN_CFG                   = 89,

    PINMUX_COMMON_PERIPHERAL_CFG        = 130,

    PINMUX_LPTIM_OUT0_CFG               = 131,
    PINMUX_LPTIM_OUT1_CFG               = 132,
    PINMUX_LPTIM_OUT2_CFG               = 133,
    PINMUX_LPTIM_OUT3_CFG               = 134,

    PINMUX_RESETB_CFG                   = 160,    /* only valid for IO13 */
    PINMUX_XTAL32K_CFG                  = 161,    /* only valid for IO24/25 */
} pinmux_t;

/// pin 0 pinmux function type
typedef enum {
    PINMUX_PAD0_JTAG_MODE_CFG           = PINMUX_JTAG_MODE_CFG,    /* TCK/SWCLK */
    PINMUX_PAD0_TIM1_OUT3_CFG           = PINMUX_TIM1_OUT3_CFG,
    PINMUX_PAD0_TIM2_ETR_CFG            = PINMUX_TIM2_ETR_CFG,
    PINMUX_PAD0_LPTIM_OUT0_CFG          = PINMUX_LPTIM_OUT0_CFG,
    PINMUX_PAD0_UART0_TRX_CFG           = PINMUX_UART0_TRX_CFG,
    PINMUX_PAD0_SPI0_DI_CFG             = PINMUX_SPI0_DI_CFG,
    PINMUX_PAD0_I2C0_SCK_CFG            = PINMUX_I2C0_SCK_CFG,
    PINMUX_PAD0_RGB_OUT_CFG             = PINMUX_RGB_OUT_CFG,
    PINMUX_PAD0_TX_EXT_PD_CFG           = PINMUX_TX_EXT_PD_CFG,
    PINMUX_PAD0_INPUT_MODE_CFG          = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD0_GPIO_MODE_CFG           = PINMUX_GPIO_MODE_CFG,
} pin_0_func_t;

/// pin 1 pinmux function type
typedef enum {
    PINMUX_PAD1_JTAG_MODE_CFG           = PINMUX_JTAG_MODE_CFG,    /* TMS/SWDIO */
    PINMUX_PAD1_TIM1_OUT2_CFG           = PINMUX_TIM1_OUT2_CFG,
    PINMUX_PAD1_TIM2_OUTN0_CFG          = PINMUX_TIM2_OUTN0_CFG,
    PINMUX_PAD1_TIM0_ETR_CFG            = PINMUX_TIM0_ETR_CFG,
    PINMUX_PAD1_LPTIM_OUT1_CFG          = PINMUX_LPTIM_OUT1_CFG,
    PINMUX_PAD1_UART0_RX_CFG            = PINMUX_UART0_RX_CFG,
    PINMUX_PAD1_UART1_CTS_CFG           = PINMUX_UART1_CTS_CFG,
    PINMUX_PAD1_SPI0_DIO_CFG            = PINMUX_SPI0_DIO_CFG,
    PINMUX_PAD1_I2C0_SDA_CFG            = PINMUX_I2C0_SDA_CFG,
    PINMUX_PAD1_IRTX_OUT_CFG            = PINMUX_IRTX_OUT_CFG,
    PINMUX_PAD1_AUDIO_EXT_CLK_CFG       = PINMUX_AUDIO_EXT_CLK_CFG,
    PINMUX_PAD1_RX_EXT_PD_CFG           = PINMUX_RX_EXT_PD_CFG,
    PINMUX_PAD1_INPUT_MODE_CFG          = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD1_GPIO_MODE_CFG           = PINMUX_GPIO_MODE_CFG,
} pin_1_func_t;

/// pin 2 pinmux function type
typedef enum {
    PINMUX_PAD2_TIM1_OUT1_CFG           = PINMUX_TIM1_OUT1_CFG,
    PINMUX_PAD2_TIM2_OUTN1_CFG          = PINMUX_TIM2_OUTN1_CFG,
    PINMUX_PAD2_TIM0_BKIN_CFG           = PINMUX_TIM0_BKIN_CFG,
    PINMUX_PAD2_LPTIM_OUT2_CFG          = PINMUX_LPTIM_OUT2_CFG,
    PINMUX_PAD2_UART2_TRX_CFG           = PINMUX_UART2_TRX_CFG,
    PINMUX_PAD2_UART1_RTS_CFG           = PINMUX_UART1_RTS_CFG,
    PINMUX_PAD2_SPI0_CS_CFG             = PINMUX_SPI0_CS_CFG,
    PINMUX_PAD2_I2C1_SCK_CFG            = PINMUX_I2C1_SCK_CFG,
    PINMUX_PAD2_QDEC_XA_CFG             = PINMUX_QDEC_XA_CFG,
    PINMUX_PAD2_I2S_SDI_CFG             = PINMUX_I2S_SDI_CFG,
    PINMUX_PAD2_RF_SDO_CFG              = PINMUX_RF_SDO_CFG,
    PINMUX_PAD2_PTA_ACTIVE_IN_CFG       = PINMUX_PTA_ACTIVE_IN_CFG,
    PINMUX_PAD2_INPUT_MODE_CFG          = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD2_GPIO_MODE_CFG           = PINMUX_GPIO_MODE_CFG,
} pin_2_func_t;

/// pin 3 pinmux function type
typedef enum {
    PINMUX_PAD3_TIM1_OUT0_CFG           = PINMUX_TIM1_OUT0_CFG,
    PINMUX_PAD3_TIM2_OUTN2_CFG          = PINMUX_TIM2_OUTN2_CFG,
    PINMUX_PAD3_TIM0_ETR_CFG            = PINMUX_TIM0_ETR_CFG,
    PINMUX_PAD3_LPTIM_OUT3_CFG          = PINMUX_LPTIM_OUT3_CFG,
    PINMUX_PAD3_UART2_RX_CFG            = PINMUX_UART2_RX_CFG,
    PINMUX_PAD3_UART1_RX_CFG            = PINMUX_UART1_RX_CFG,
    PINMUX_PAD3_SPI0_SCK_CFG            = PINMUX_SPI0_SCK_CFG,
    PINMUX_PAD3_I2C1_SDA_CFG            = PINMUX_I2C1_SDA_CFG,
    PINMUX_PAD3_QDEC_XB_CFG             = PINMUX_QDEC_XB_CFG,
    PINMUX_PAD3_I2S_SDO_CFG             = PINMUX_I2S_SDO_CFG,
    PINMUX_PAD3_RF_SCK_CFG              = PINMUX_RF_SCK_CFG,
    PINMUX_PAD3_PTA_ACTIVE_OUT_CFG      = PINMUX_PTA_ACTIVE_OUT_CFG,
    PINMUX_PAD3_INPUT_MODE_CFG          = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD3_GPIO_MODE_CFG           = PINMUX_GPIO_MODE_CFG,
} pin_3_func_t;

/// pin 4 pinmux function type
typedef enum {
    PINMUX_PAD4_TIM0_IO0_CFG            = PINMUX_TIM0_IO0_CFG,
    PINMUX_PAD4_TIM1_ETR_CFG            = PINMUX_TIM1_ETR_CFG,
    PINMUX_PAD4_DMIC_IN_CFG             = PINMUX_DMIC_IN_CFG,
    PINMUX_PAD4_UART2_TRX_CFG           = PINMUX_UART2_TRX_CFG,
    PINMUX_PAD4_UART1_TRX_CFG           = PINMUX_UART1_TRX_CFG,
    PINMUX_PAD4_SPI1_DI_CFG             = PINMUX_SPI1_DI_CFG,
    PINMUX_PAD4_I2C0_SCK_CFG            = PINMUX_I2C0_SCK_CFG,
    PINMUX_PAD4_QDEC_LED_CFG            = PINMUX_QDEC_LED_CFG,
    PINMUX_PAD4_I2S_WS_CFG              = PINMUX_I2S_WS_CFG,
    PINMUX_PAD4_PTA_PRIORITY_CFG        = PINMUX_PTA_PRIORITY_CFG,
    PINMUX_PAD4_INPUT_MODE_CFG          = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD4_GPIO_MODE_CFG           = PINMUX_GPIO_MODE_CFG,
} pin_4_func_t;

/// pin 5 pinmux function type
typedef enum {
    PINMUX_PAD5_TIM0_IO1_CFG            = PINMUX_TIM0_IO1_CFG,
    PINMUX_PAD5_TIM1_OUTN0_CFG          = PINMUX_TIM1_OUTN0_CFG,
    PINMUX_PAD5_TIM2_BKIN_CFG           = PINMUX_TIM2_BKIN_CFG,
    PINMUX_PAD5_DMIC_CLK_CFG            = PINMUX_DMIC_CLK_CFG,
    PINMUX_PAD5_UART0_TRX_CFG           = PINMUX_UART0_TRX_CFG,
    PINMUX_PAD5_UART1_TRX_CFG           = PINMUX_UART1_TRX_CFG,
    PINMUX_PAD5_SPI1_DIO_CFG            = PINMUX_SPI1_DIO_CFG,
    PINMUX_PAD5_I2C0_SDA_CFG            = PINMUX_I2C0_SDA_CFG,
    PINMUX_PAD5_RGB_OUT_CFG             = PINMUX_RGB_OUT_CFG,
    PINMUX_PAD5_I2S_SCLK_CFG            = PINMUX_I2S_SCLK_CFG,
    PINMUX_PAD5_PTA_FREQ_CFG            = PINMUX_PTA_FREQ_CFG,
    PINMUX_PAD5_INPUT_MODE_CFG          = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD5_GPIO_MODE_CFG           = PINMUX_GPIO_MODE_CFG,
} pin_5_func_t;

/// pin 6 pinmux function type
typedef enum {
    PINMUX_PAD6_TIM0_IO2_CFG            = PINMUX_TIM0_IO2_CFG,
    PINMUX_PAD6_TIM1_OUTN1_CFG          = PINMUX_TIM1_OUTN1_CFG,
    PINMUX_PAD6_TIM2_ETR_CFG            = PINMUX_TIM2_ETR_CFG,
    PINMUX_PAD6_LPTIM_OUT0_CFG          = PINMUX_LPTIM_OUT0_CFG,
    PINMUX_PAD6_UART0_RX_CFG            = PINMUX_UART0_RX_CFG,
    PINMUX_PAD6_UART1_RX_CFG            = PINMUX_UART1_RX_CFG,
    PINMUX_PAD6_SPI1_CS_CFG             = PINMUX_SPI1_CS_CFG,
    PINMUX_PAD6_I2C1_SCK_CFG            = PINMUX_I2C1_SCK_CFG,
    PINMUX_PAD6_IRTX_OUT_CFG            = PINMUX_IRTX_OUT_CFG,
    PINMUX_PAD6_AUDIO_EXT_CLK_CFG       = PINMUX_AUDIO_EXT_CLK_CFG,
    PINMUX_PAD6_TX_EXT_PD_CFG           = PINMUX_TX_EXT_PD_CFG,
    PINMUX_PAD6_INPUT_MODE_CFG          = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD6_GPIO_MODE_CFG           = PINMUX_GPIO_MODE_CFG,
} pin_6_func_t;

/// pin 7 pinmux function type
typedef enum {
    PINMUX_PAD7_JTAG_MODE_CFG           = PINMUX_JTAG_MODE_CFG,    /* TRST */
    PINMUX_PAD7_TIM0_IO3_CFG            = PINMUX_TIM0_IO3_CFG,
    PINMUX_PAD7_TIM1_OUTN2_CFG          = PINMUX_TIM1_OUTN2_CFG,
    PINMUX_PAD7_TIM2_BKIN_CFG           = PINMUX_TIM2_BKIN_CFG,
    PINMUX_PAD7_LPTIM_OUT1_CFG          = PINMUX_LPTIM_OUT1_CFG,
    PINMUX_PAD7_UART2_RX_CFG            = PINMUX_UART2_RX_CFG,
    PINMUX_PAD7_UART1_CTS_CFG           = PINMUX_UART1_CTS_CFG,
    PINMUX_PAD7_SPI1_SCK_CFG            = PINMUX_SPI1_SCK_CFG,
    PINMUX_PAD7_I2C1_SDA_CFG            = PINMUX_I2C1_SDA_CFG,
    PINMUX_PAD7_OSPI1_SO_CFG            = PINMUX_OSPI1_SO_CFG,
    PINMUX_PAD7_QDEC_XA_CFG             = PINMUX_QDEC_XA_CFG,
    PINMUX_PAD7_I2S_SDI_CFG             = PINMUX_I2S_SDI_CFG,
    PINMUX_PAD7_RX_EXT_PD_CFG           = PINMUX_RX_EXT_PD_CFG,
    PINMUX_PAD7_INPUT_MODE_CFG          = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD7_GPIO_MODE_CFG           = PINMUX_GPIO_MODE_CFG,
} pin_7_func_t;

/// pin 8 pinmux function type
typedef enum {
    PINMUX_PAD8_JTAG_MODE_CFG           = PINMUX_JTAG_MODE_CFG,    /* TDI */
    PINMUX_PAD8_TIM2_OUT0_CFG           = PINMUX_TIM2_OUT0_CFG,
    PINMUX_PAD8_TIM0_BKIN_CFG           = PINMUX_TIM0_BKIN_CFG,
    PINMUX_PAD8_LPTIM_OUT2_CFG          = PINMUX_LPTIM_OUT2_CFG,
    PINMUX_PAD8_UART0_TRX_CFG           = PINMUX_UART0_TRX_CFG,
    PINMUX_PAD8_UART1_RTS_CFG           = PINMUX_UART1_RTS_CFG,
    PINMUX_PAD8_SPI0_DI_CFG             = PINMUX_SPI0_DI_CFG,
    PINMUX_PAD8_I2C0_SCK_CFG            = PINMUX_I2C0_SCK_CFG,
    PINMUX_PAD8_OSPI1_CS_CFG            = PINMUX_OSPI1_CS_CFG,
    PINMUX_PAD8_QDEC_XB_CFG             = PINMUX_QDEC_XB_CFG,
    PINMUX_PAD8_I2S_SDO_CFG             = PINMUX_I2S_SDO_CFG,
    PINMUX_PAD8_PTA_ACTIVE_IN_CFG       = PINMUX_PTA_ACTIVE_IN_CFG,
    PINMUX_PAD8_INPUT_MODE_CFG          = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD8_GPIO_MODE_CFG           = PINMUX_GPIO_MODE_CFG,
} pin_8_func_t;

/// pin 9 pinmux function type
typedef enum {
    PINMUX_PAD9_JTAG_MODE_CFG           = PINMUX_JTAG_MODE_CFG,    /* TDO */
    PINMUX_PAD9_TIM2_OUT1_CFG           = PINMUX_TIM2_OUT1_CFG,
    PINMUX_PAD9_TIM0_OUTN0_CFG          = PINMUX_TIM0_OUTN0_CFG,
    PINMUX_PAD9_TIM1_BKIN_CFG           = PINMUX_TIM1_BKIN_CFG,
    PINMUX_PAD9_LPTIM_OUT3_CFG          = PINMUX_LPTIM_OUT3_CFG,
    PINMUX_PAD9_UART0_RX_CFG            = PINMUX_UART0_RX_CFG,
    PINMUX_PAD9_UART1_RX_CFG            = PINMUX_UART1_RX_CFG,
    PINMUX_PAD9_SPI0_DIO_CFG            = PINMUX_SPI0_DIO_CFG,
    PINMUX_PAD9_I2C0_SDA_CFG            = PINMUX_I2C0_SDA_CFG,
    PINMUX_PAD9_OSPI1_CK_CFG            = PINMUX_OSPI1_CK_CFG,
    PINMUX_PAD9_QDEC_LED_CFG            = PINMUX_QDEC_LED_CFG,
    PINMUX_PAD9_I2S_WS_CFG              = PINMUX_I2S_WS_CFG,
    PINMUX_PAD9_PTA_ACTIVE_OUT_CFG      = PINMUX_PTA_ACTIVE_OUT_CFG,
    PINMUX_PAD9_INPUT_MODE_CFG          = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD9_GPIO_MODE_CFG           = PINMUX_GPIO_MODE_CFG,
} pin_9_func_t;

/// pin 10 pinmux function type
typedef enum {
    PINMUX_PAD10_TIM2_OUT2_CFG          = PINMUX_TIM2_OUT2_CFG,
    PINMUX_PAD10_TIM0_OUTN1_CFG         = PINMUX_TIM0_OUTN1_CFG,
    PINMUX_PAD10_TIM1_ETR_CFG           = PINMUX_TIM1_ETR_CFG,
    PINMUX_PAD10_DMIC_IN_CFG            = PINMUX_DMIC_IN_CFG,
    PINMUX_PAD10_UART2_TRX_CFG          = PINMUX_UART2_TRX_CFG,
    PINMUX_PAD10_UART1_TRX_CFG          = PINMUX_UART1_TRX_CFG,
    PINMUX_PAD10_SPI0_CS_CFG            = PINMUX_SPI0_CS_CFG,
    PINMUX_PAD10_I2C1_SCK_CFG           = PINMUX_I2C1_SCK_CFG,
    PINMUX_PAD10_OSPI1_SI_CFG           = PINMUX_OSPI1_SI_CFG,
    PINMUX_PAD10_RGB_OUT_CFG            = PINMUX_RGB_OUT_CFG,
    PINMUX_PAD10_I2S_SCLK_CFG           = PINMUX_I2S_SCLK_CFG,
    PINMUX_PAD10_PTA_PRIORITY_CFG       = PINMUX_PTA_PRIORITY_CFG,
    PINMUX_PAD10_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD10_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_10_func_t;

/// pin 11 pinmux function type
typedef enum {
    PINMUX_PAD11_TIM2_OUT3_CFG          = PINMUX_TIM2_OUT3_CFG,
    PINMUX_PAD11_TIM0_OUTN2_CFG         = PINMUX_TIM0_OUTN2_CFG,
    PINMUX_PAD11_TIM1_BKIN_CFG          = PINMUX_TIM1_BKIN_CFG,
    PINMUX_PAD11_DMIC_CLK_CFG           = PINMUX_DMIC_CLK_CFG,
    PINMUX_PAD11_UART2_RX_CFG           = PINMUX_UART2_RX_CFG,
    PINMUX_PAD11_UART1_CTS_CFG          = PINMUX_UART1_CTS_CFG,
    PINMUX_PAD11_SPI0_SCK_CFG           = PINMUX_SPI0_SCK_CFG,
    PINMUX_PAD11_I2C1_SDA_CFG           = PINMUX_I2C1_SDA_CFG,
    PINMUX_PAD11_OSPI1_HD_CFG           = PINMUX_OSPI1_HD_CFG,
    PINMUX_PAD11_IRTX_OUT_CFG           = PINMUX_IRTX_OUT_CFG,
    PINMUX_PAD11_AUDIO_EXT_CLK_CFG      = PINMUX_AUDIO_EXT_CLK_CFG,
    PINMUX_PAD11_PTA_FREQ_CFG           = PINMUX_PTA_FREQ_CFG,
    PINMUX_PAD11_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD11_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_11_func_t;

/// pin 12 pinmux function type
typedef enum {
    PINMUX_PAD12_TIM1_OUT0_CFG          = PINMUX_TIM1_OUT0_CFG,
    PINMUX_PAD12_TIM2_ETR_CFG           = PINMUX_TIM2_ETR_CFG,
    PINMUX_PAD12_LPTIM_OUT0_CFG         = PINMUX_LPTIM_OUT0_CFG,
    PINMUX_PAD12_UART0_TRX_CFG          = PINMUX_UART0_TRX_CFG,
    PINMUX_PAD12_UART1_RTS_CFG          = PINMUX_UART1_RTS_CFG,
    PINMUX_PAD12_SPI1_DI_CFG            = PINMUX_SPI1_DI_CFG,
    PINMUX_PAD12_I2C0_SCK_CFG           = PINMUX_I2C0_SCK_CFG,
    PINMUX_PAD12_OSPI1_WP_CFG           = PINMUX_OSPI1_WP_CFG,
    PINMUX_PAD12_QDEC_XA_CFG            = PINMUX_QDEC_XA_CFG,
    PINMUX_PAD12_I2S_SDI_CFG            = PINMUX_I2S_SDI_CFG,
    PINMUX_PAD12_TX_EXT_PD_CFG          = PINMUX_TX_EXT_PD_CFG,
    PINMUX_PAD12_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD12_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_12_func_t;

/// pin 13 pinmux function type
typedef enum {
    PINMUX_PAD13_TIM1_OUT1_CFG          = PINMUX_TIM1_OUT1_CFG,
    PINMUX_PAD13_TIM2_OUTN0_CFG         = PINMUX_TIM2_OUTN0_CFG,
    PINMUX_PAD13_TIM0_ETR_CFG           = PINMUX_TIM0_ETR_CFG,
    PINMUX_PAD13_LPTIM_OUT1_CFG         = PINMUX_LPTIM_OUT1_CFG,
    PINMUX_PAD13_UART0_RX_CFG           = PINMUX_UART0_RX_CFG,
    PINMUX_PAD13_UART1_RX_CFG           = PINMUX_UART1_RX_CFG,
    PINMUX_PAD13_SPI1_DIO_CFG           = PINMUX_SPI1_DIO_CFG,
    PINMUX_PAD13_I2C0_SDA_CFG           = PINMUX_I2C0_SDA_CFG,
    PINMUX_PAD13_QDEC_XB_CFG            = PINMUX_QDEC_XB_CFG,
    PINMUX_PAD13_I2S_SDO_CFG            = PINMUX_I2S_SDO_CFG,
    PINMUX_PAD13_RF_CSN_CFG             = PINMUX_RF_CSN_CFG,
    PINMUX_PAD13_RX_EXT_PD_CFG          = PINMUX_RX_EXT_PD_CFG,
    PINMUX_PAD13_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD13_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
    PINMUX_PAD13_RESETB_CFG             = PINMUX_RESETB_CFG,
} pin_13_func_t;

/// pin 14 pinmux function type
typedef enum {
    PINMUX_PAD14_TIM1_OUT2_CFG          = PINMUX_TIM1_OUT2_CFG,
    PINMUX_PAD14_TIM2_OUTN1_CFG         = PINMUX_TIM2_OUTN1_CFG,
    PINMUX_PAD14_TIM0_BKIN_CFG          = PINMUX_TIM0_BKIN_CFG,
    PINMUX_PAD14_LPTIM_OUT2_CFG         = PINMUX_LPTIM_OUT2_CFG,
    PINMUX_PAD14_UART2_TRX_CFG          = PINMUX_UART2_TRX_CFG,
    PINMUX_PAD14_UART1_TRX_CFG          = PINMUX_UART1_TRX_CFG,
    PINMUX_PAD14_SPI1_CS_CFG            = PINMUX_SPI1_CS_CFG,
    PINMUX_PAD14_I2C1_SCK_CFG           = PINMUX_I2C1_SCK_CFG,
    PINMUX_PAD14_LCD_SCK_CFG            = PINMUX_LCD_CK_CFG,
    PINMUX_PAD14_QDEC_LED_CFG           = PINMUX_QDEC_LED_CFG,
    PINMUX_PAD14_I2S_WS_CFG             = PINMUX_I2S_WS_CFG,
    PINMUX_PAD14_PTA_ACTIVE_IN_CFG      = PINMUX_PTA_ACTIVE_IN_CFG,
    PINMUX_PAD14_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD14_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_14_func_t;

/// pin 15 pinmux function type
typedef enum {
    PINMUX_PAD15_TIM1_OUT3_CFG          = PINMUX_TIM1_OUT3_CFG,
    PINMUX_PAD15_TIM2_OUTN2_CFG         = PINMUX_TIM2_OUTN2_CFG,
    PINMUX_PAD15_TIM0_ETR_CFG           = PINMUX_TIM0_ETR_CFG,
    PINMUX_PAD15_LPTIM_OUT3_CFG         = PINMUX_LPTIM_OUT3_CFG,
    PINMUX_PAD15_UART2_RX_CFG           = PINMUX_UART2_RX_CFG,
    PINMUX_PAD15_UART1_CTS_CFG          = PINMUX_UART1_CTS_CFG,
    PINMUX_PAD15_SPI1_SCK_CFG           = PINMUX_SPI1_SCK_CFG,
    PINMUX_PAD15_I2C1_SDA_CFG           = PINMUX_I2C1_SDA_CFG,
    PINMUX_PAD15_LCD_IO1_CFG            = PINMUX_LCD_SO_CFG,
    PINMUX_PAD15_RGB_OUT_CFG            = PINMUX_RGB_OUT_CFG,
    PINMUX_PAD15_I2S_SCLK_CFG           = PINMUX_I2S_SCLK_CFG,
    PINMUX_PAD15_PTA_ACTIVE_OUT_CFG     = PINMUX_PTA_ACTIVE_OUT_CFG,
    PINMUX_PAD15_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD15_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_15_func_t;

/// pin 16 pinmux function type
typedef enum {
    PINMUX_PAD16_TIM0_IO0_CFG           = PINMUX_TIM0_IO0_CFG,
    PINMUX_PAD16_TIM1_ETR_CFG           = PINMUX_TIM1_ETR_CFG,
    PINMUX_PAD16_DMIC_IN_CFG            = PINMUX_DMIC_IN_CFG,
    PINMUX_PAD16_UART0_TRX_CFG          = PINMUX_UART0_TRX_CFG,
    PINMUX_PAD16_UART1_RTS_CFG          = PINMUX_UART1_RTS_CFG,
    PINMUX_PAD16_SPI0_DI_CFG            = PINMUX_SPI0_DI_CFG,
    PINMUX_PAD16_I2C0_SCK_CFG           = PINMUX_I2C0_SCK_CFG,
    PINMUX_PAD16_IRTX_OUT_CFG           = PINMUX_IRTX_OUT_CFG,
    PINMUX_PAD16_AUDIO_EXT_CLK_CFG      = PINMUX_AUDIO_EXT_CLK_CFG,
    PINMUX_PAD16_USB_DM_CFG             = PINMUX_USB_DM_CFG,
    PINMUX_PAD16_PTA_PRIORITY_CFG       = PINMUX_PTA_PRIORITY_CFG,
    PINMUX_PAD16_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD16_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_16_func_t;

/// pin 17 pinmux function type
typedef enum {
    PINMUX_PAD17_TIM0_IO1_CFG           = PINMUX_TIM0_IO1_CFG,
    PINMUX_PAD17_TIM1_OUTN0_CFG         = PINMUX_TIM1_OUTN0_CFG,
    PINMUX_PAD17_TIM2_BKIN_CFG          = PINMUX_TIM2_BKIN_CFG,
    PINMUX_PAD17_DMIC_CLK_CFG           = PINMUX_DMIC_CLK_CFG,
    PINMUX_PAD17_UART0_RX_CFG           = PINMUX_UART0_RX_CFG,
    PINMUX_PAD17_UART1_RX_CFG           = PINMUX_UART1_RX_CFG,
    PINMUX_PAD17_SPI0_DIO_CFG           = PINMUX_SPI0_DIO_CFG,
    PINMUX_PAD17_I2C0_SDA_CFG           = PINMUX_I2C0_SDA_CFG,
    PINMUX_PAD17_QDEC_XA_CFG            = PINMUX_QDEC_XA_CFG,
    PINMUX_PAD17_I2S_SDI_CFG            = PINMUX_I2S_SDI_CFG,
    PINMUX_PAD17_USB_DP_CFG             = PINMUX_USB_DP_CFG,
    PINMUX_PAD17_PTA_FREQ_CFG           = PINMUX_PTA_FREQ_CFG,
    PINMUX_PAD17_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD17_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_17_func_t;

/// pin 18 pinmux function type
typedef enum {
    PINMUX_PAD18_TIM0_IO2_CFG           = PINMUX_TIM0_IO2_CFG,
    PINMUX_PAD18_TIM1_OUTN1_CFG         = PINMUX_TIM1_OUTN1_CFG,
    PINMUX_PAD18_TIM2_ETR_CFG           = PINMUX_TIM2_ETR_CFG,
    PINMUX_PAD18_LPTIM_OUT0_CFG         = PINMUX_LPTIM_OUT0_CFG,
    PINMUX_PAD18_UART2_TRX_CFG          = PINMUX_UART2_TRX_CFG,
    PINMUX_PAD18_UART1_TRX_CFG          = PINMUX_UART1_TRX_CFG,
    PINMUX_PAD18_SPI0_CS_CFG            = PINMUX_SPI0_CS_CFG,
    PINMUX_PAD18_I2C1_SCK_CFG           = PINMUX_I2C1_SCK_CFG,
    PINMUX_PAD18_LCD_IO0_CFG            = PINMUX_LCD_SI_CFG,
    PINMUX_PAD18_QDEC_XB_CFG            = PINMUX_QDEC_XB_CFG,
    PINMUX_PAD18_I2S_SDO_CFG            = PINMUX_I2S_SDO_CFG,
    PINMUX_PAD18_TX_EXT_PD_CFG          = PINMUX_TX_EXT_PD_CFG,
    PINMUX_PAD18_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD18_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_18_func_t;

/// pin 19 pinmux function type
typedef enum {
    PINMUX_PAD19_TIM0_IO3_CFG           = PINMUX_TIM0_IO3_CFG,
    PINMUX_PAD19_TIM1_OUTN2_CFG         = PINMUX_TIM1_OUTN2_CFG,
    PINMUX_PAD19_TIM2_BKIN_CFG          = PINMUX_TIM2_BKIN_CFG,
    PINMUX_PAD19_LPTIM_OUT1_CFG         = PINMUX_LPTIM_OUT1_CFG,
    PINMUX_PAD19_UART2_RX_CFG           = PINMUX_UART2_RX_CFG,
    PINMUX_PAD19_UART1_CTS_CFG          = PINMUX_UART1_CTS_CFG,
    PINMUX_PAD19_SPI0_SCK_CFG           = PINMUX_SPI0_SCK_CFG,
    PINMUX_PAD19_I2C1_SDA_CFG           = PINMUX_I2C1_SDA_CFG,
    PINMUX_PAD19_LCD_IO3_CFG            = PINMUX_LCD_HD_CFG,
    PINMUX_PAD19_QDEC_LED_CFG           = PINMUX_QDEC_LED_CFG,
    PINMUX_PAD19_I2S_WS_CFG             = PINMUX_I2S_WS_CFG,
    PINMUX_PAD19_RX_EXT_PD_CFG          = PINMUX_RX_EXT_PD_CFG,
    PINMUX_PAD19_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD19_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_19_func_t;

/// pin 20 pinmux function type
typedef enum {
    PINMUX_PAD20_TIM2_OUT0_CFG          = PINMUX_TIM2_OUT0_CFG,
    PINMUX_PAD20_TIM0_BKIN_CFG          = PINMUX_TIM0_BKIN_CFG,
    PINMUX_PAD20_LPTIM_OUT2_CFG         = PINMUX_LPTIM_OUT2_CFG,
    PINMUX_PAD20_UART0_TRX_CFG          = PINMUX_UART0_TRX_CFG,
    PINMUX_PAD20_UART1_RTS_CFG          = PINMUX_UART1_RTS_CFG,
    PINMUX_PAD20_SPI1_DI_CFG            = PINMUX_SPI1_DI_CFG,
    PINMUX_PAD20_I2C0_SCK_CFG           = PINMUX_I2C0_SCK_CFG,
    PINMUX_PAD20_LCD_IO2_CFG            = PINMUX_LCD_WP_CFG,
    PINMUX_PAD20_LCD_DCX_RS_CFG         = PINMUX_LCD_WP_CFG,
    PINMUX_PAD20_RGB_OUT_CFG            = PINMUX_RGB_OUT_CFG,
    PINMUX_PAD20_I2S_SCLK_CFG           = PINMUX_I2S_SCLK_CFG,
    PINMUX_PAD20_PTA_ACTIVE_IN_CFG      = PINMUX_PTA_ACTIVE_IN_CFG,
    PINMUX_PAD20_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD20_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_20_func_t;

/// pin 21 pinmux function type
typedef enum {
    PINMUX_PAD21_TIM2_OUT1_CFG          = PINMUX_TIM2_OUT1_CFG,
    PINMUX_PAD21_TIM0_OUTN0_CFG         = PINMUX_TIM0_OUTN0_CFG,
    PINMUX_PAD21_TIM1_BKIN_CFG          = PINMUX_TIM1_BKIN_CFG,
    PINMUX_PAD21_LPTIM_OUT3_CFG         = PINMUX_LPTIM_OUT3_CFG,
    PINMUX_PAD21_UART0_RX_CFG           = PINMUX_UART0_RX_CFG,
    PINMUX_PAD21_UART1_RX_CFG           = PINMUX_UART1_RX_CFG,
    PINMUX_PAD21_SPI1_DIO_CFG           = PINMUX_SPI1_DIO_CFG,
    PINMUX_PAD21_I2C0_SDA_CFG           = PINMUX_I2C0_SDA_CFG,
    PINMUX_PAD21_LCD_CS0_CFG            = PINMUX_LCD_CS0_CFG,
    PINMUX_PAD21_IRTX_OUT_CFG           = PINMUX_IRTX_OUT_CFG,
    PINMUX_PAD21_AUDIO_EXT_CLK_CFG      = PINMUX_AUDIO_EXT_CLK_CFG,
    PINMUX_PAD21_PTA_ACTIVE_OUT_CFG     = PINMUX_PTA_ACTIVE_OUT_CFG,
    PINMUX_PAD21_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD21_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_21_func_t;

/// pin 22 pinmux function type
typedef enum {
    PINMUX_PAD22_TIM2_OUT2_CFG          = PINMUX_TIM2_OUT2_CFG,
    PINMUX_PAD22_TIM0_OUTN1_CFG         = PINMUX_TIM0_OUTN1_CFG,
    PINMUX_PAD22_TIM1_ETR_CFG           = PINMUX_TIM1_ETR_CFG,
    PINMUX_PAD22_DMIC_IN_CFG            = PINMUX_DMIC_IN_CFG,
    PINMUX_PAD22_UART2_TRX_CFG          = PINMUX_UART2_TRX_CFG,
    PINMUX_PAD22_UART1_TRX_CFG          = PINMUX_UART1_TRX_CFG,
    PINMUX_PAD22_SPI1_CS_CFG            = PINMUX_SPI1_CS_CFG,
    PINMUX_PAD22_I2C1_SCK_CFG           = PINMUX_I2C1_SCK_CFG,
    PINMUX_PAD22_QDEC_XA_CFG            = PINMUX_QDEC_XA_CFG,
    PINMUX_PAD22_I2S_SDI_CFG            = PINMUX_I2S_SDI_CFG,
    PINMUX_PAD22_PTA_PRIORITY_CFG       = PINMUX_PTA_PRIORITY_CFG,
    PINMUX_PAD22_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD22_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_22_func_t;

/// pin 23 pinmux function type
typedef enum {
    PINMUX_PAD23_TIM2_OUT3_CFG          = PINMUX_TIM2_OUT3_CFG,
    PINMUX_PAD23_TIM0_OUTN2_CFG         = PINMUX_TIM0_OUTN2_CFG,
    PINMUX_PAD23_TIM1_BKIN_CFG          = PINMUX_TIM1_BKIN_CFG,
    PINMUX_PAD23_DMIC_CLK_CFG           = PINMUX_DMIC_CLK_CFG,
    PINMUX_PAD23_UART2_RX_CFG           = PINMUX_UART2_RX_CFG,
    PINMUX_PAD23_UART1_CTS_CFG          = PINMUX_UART1_CTS_CFG,
    PINMUX_PAD23_SPI1_SCK_CFG           = PINMUX_SPI1_SCK_CFG,
    PINMUX_PAD23_I2C1_SDA_CFG           = PINMUX_I2C1_SDA_CFG,
    PINMUX_PAD23_QDEC_XB_CFG            = PINMUX_QDEC_XB_CFG,
    PINMUX_PAD23_I2S_SDO_CFG            = PINMUX_I2S_SDO_CFG,
    PINMUX_PAD23_USB_OTG_VBUS_EN_CFG    = PINMUX_USB_OTG_VBUS_EN_CFG,
    PINMUX_PAD23_PTA_FREQ_CFG           = PINMUX_PTA_FREQ_CFG,
    PINMUX_PAD23_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD23_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_23_func_t;

/// pin 24 pinmux function type
typedef enum {
    PINMUX_PAD24_TIM0_IO0_CFG           = PINMUX_TIM0_IO0_CFG,
    PINMUX_PAD24_TIM2_ETR_CFG           = PINMUX_TIM2_ETR_CFG,
    PINMUX_PAD24_LPTIM_OUT0_CFG         = PINMUX_LPTIM_OUT0_CFG,
    PINMUX_PAD24_UART0_TRX_CFG          = PINMUX_UART0_TRX_CFG,
    PINMUX_PAD24_UART1_RX_CFG           = PINMUX_UART1_RX_CFG,
    PINMUX_PAD24_SPI0_DI_CFG            = PINMUX_SPI0_DI_CFG,
    PINMUX_PAD24_I2C0_SCK_CFG           = PINMUX_I2C0_SCK_CFG,
    PINMUX_PAD24_QDEC_LED_CFG           = PINMUX_QDEC_LED_CFG,
    PINMUX_PAD24_I2S_WS_CFG             = PINMUX_I2S_WS_CFG,
    PINMUX_PAD24_TX_EXT_PD_CFG          = PINMUX_TX_EXT_PD_CFG,
    PINMUX_PAD24_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD24_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
    PINMUX_PAD24_XTAL32K_CFG            = PINMUX_XTAL32K_CFG,
} pin_24_func_t;

/// pin 25 pinmux function type
typedef enum {
    PINMUX_PAD25_TIM0_IO1_CFG           = PINMUX_TIM0_IO1_CFG,
    PINMUX_PAD25_TIM2_OUTN0_CFG         = PINMUX_TIM2_OUTN0_CFG,
    PINMUX_PAD25_TIM0_ETR_CFG           = PINMUX_TIM0_ETR_CFG,
    PINMUX_PAD25_LPTIM_OUT1_CFG         = PINMUX_LPTIM_OUT1_CFG,
    PINMUX_PAD25_UART0_RX_CFG           = PINMUX_UART0_RX_CFG,
    PINMUX_PAD25_UART1_TRX_CFG          = PINMUX_UART1_TRX_CFG,
    PINMUX_PAD25_SPI0_DIO_CFG           = PINMUX_SPI0_DIO_CFG,
    PINMUX_PAD25_I2C0_SDA_CFG           = PINMUX_I2C0_SDA_CFG,
    PINMUX_PAD25_RGB_OUT_CFG            = PINMUX_RGB_OUT_CFG,
    PINMUX_PAD25_I2S_SCLK_CFG           = PINMUX_I2S_SCLK_CFG,
    PINMUX_PAD25_RX_EXT_PD_CFG          = PINMUX_RX_EXT_PD_CFG,
    PINMUX_PAD25_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD25_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
    PINMUX_PAD25_XTAL32K_CFG            = PINMUX_XTAL32K_CFG,
} pin_25_func_t;

/// pin 26 pinmux function type
typedef enum {
    PINMUX_PAD26_TIM1_OUT2_CFG          = PINMUX_TIM1_OUT2_CFG,
    PINMUX_PAD26_TIM2_OUTN1_CFG         = PINMUX_TIM2_OUTN1_CFG,
    PINMUX_PAD26_TIM0_BKIN_CFG          = PINMUX_TIM0_BKIN_CFG,
    PINMUX_PAD26_LPTIM_OUT2_CFG         = PINMUX_LPTIM_OUT2_CFG,
    PINMUX_PAD26_UART2_TRX_CFG          = PINMUX_UART2_TRX_CFG,
    PINMUX_PAD26_UART1_TRX_CFG          = PINMUX_UART1_TRX_CFG,
    PINMUX_PAD26_SPI0_CS_CFG            = PINMUX_SPI0_CS_CFG,
    PINMUX_PAD26_I2C1_SCK_CFG           = PINMUX_I2C1_SCK_CFG,
    PINMUX_PAD26_IRTX_OUT_CFG           = PINMUX_IRTX_OUT_CFG,
    PINMUX_PAD26_AUDIO_EXT_CLK_CFG      = PINMUX_AUDIO_EXT_CLK_CFG,
    PINMUX_PAD26_PTA_ACTIVE_IN_CFG      = PINMUX_PTA_ACTIVE_IN_CFG,
    PINMUX_PAD26_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD26_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_26_func_t;

/// pin 27 pinmux function type
typedef enum {
    PINMUX_PAD27_TIM1_OUT3_CFG          = PINMUX_TIM1_OUT3_CFG,
    PINMUX_PAD27_TIM2_OUTN2_CFG         = PINMUX_TIM2_OUTN2_CFG,
    PINMUX_PAD27_TIM0_ETR_CFG           = PINMUX_TIM0_ETR_CFG,
    PINMUX_PAD27_LPTIM_OUT3_CFG         = PINMUX_LPTIM_OUT3_CFG,
    PINMUX_PAD27_UART2_RX_CFG           = PINMUX_UART2_RX_CFG,
    PINMUX_PAD27_UART1_CTS_CFG          = PINMUX_UART1_CTS_CFG,
    PINMUX_PAD27_SPI0_SCK_CFG           = PINMUX_SPI0_SCK_CFG,
    PINMUX_PAD27_I2C1_SDA_CFG           = PINMUX_I2C1_SDA_CFG,
    PINMUX_PAD27_QDEC_XA_CFG            = PINMUX_QDEC_XA_CFG,
    PINMUX_PAD27_I2S_SDI_CFG            = PINMUX_I2S_SDI_CFG,
    PINMUX_PAD27_PTA_ACTIVE_OUT_CFG     = PINMUX_PTA_ACTIVE_OUT_CFG,
    PINMUX_PAD27_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD27_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_27_func_t;

/// pin 28 pinmux function type
typedef enum {
    PINMUX_PAD28_TIM0_IO0_CFG           = PINMUX_TIM0_IO0_CFG,
    PINMUX_PAD28_TIM1_ETR_CFG           = PINMUX_TIM1_ETR_CFG,
    PINMUX_PAD28_DMIC_IN_CFG            = PINMUX_DMIC_IN_CFG,
    PINMUX_PAD28_UART0_TRX_CFG          = PINMUX_UART0_TRX_CFG,
    PINMUX_PAD28_UART1_RTS_CFG          = PINMUX_UART1_RTS_CFG,
    PINMUX_PAD28_SPI1_DI_CFG            = PINMUX_SPI1_DI_CFG,
    PINMUX_PAD28_I2C0_SCK_CFG           = PINMUX_I2C0_SCK_CFG,
    PINMUX_PAD28_QDEC_XB_CFG            = PINMUX_QDEC_XB_CFG,
    PINMUX_PAD28_I2S_SDO_CFG            = PINMUX_I2S_SDO_CFG,
    PINMUX_PAD28_PTA_PRIORITY_CFG       = PINMUX_PTA_PRIORITY_CFG,
    PINMUX_PAD28_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD28_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_28_func_t;

/// pin 29 pinmux function type
typedef enum {
    PINMUX_PAD29_TIM0_IO1_CFG           = PINMUX_TIM0_IO1_CFG,
    PINMUX_PAD29_TIM1_OUTN0_CFG         = PINMUX_TIM1_OUTN0_CFG,
    PINMUX_PAD29_TIM2_BKIN_CFG          = PINMUX_TIM2_BKIN_CFG,
    PINMUX_PAD29_DMIC_CLK_CFG           = PINMUX_DMIC_CLK_CFG,
    PINMUX_PAD29_UART0_RX_CFG           = PINMUX_UART0_RX_CFG,
    PINMUX_PAD29_UART1_RX_CFG           = PINMUX_UART1_RX_CFG,
    PINMUX_PAD29_SPI1_DIO_CFG           = PINMUX_SPI1_DIO_CFG,
    PINMUX_PAD29_I2C0_SDA_CFG           = PINMUX_I2C0_SDA_CFG,
    PINMUX_PAD29_LCD_CS1_CFG            = PINMUX_LCD_CS1_CFG,
    PINMUX_PAD29_QDEC_LED_CFG           = PINMUX_QDEC_LED_CFG,
    PINMUX_PAD29_I2S_WS_CFG             = PINMUX_I2S_WS_CFG,
    PINMUX_PAD29_PTA_FREQ_CFG           = PINMUX_PTA_FREQ_CFG,
    PINMUX_PAD29_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD29_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_29_func_t;

/// pin 30 pinmux function type
typedef enum {
    PINMUX_PAD30_TIM0_IO2_CFG           = PINMUX_TIM0_IO2_CFG,
    PINMUX_PAD30_TIM1_OUTN1_CFG         = PINMUX_TIM1_OUTN1_CFG,
    PINMUX_PAD30_TIM2_ETR_CFG           = PINMUX_TIM2_ETR_CFG,
    PINMUX_PAD30_LPTIM_OUT0_CFG         = PINMUX_LPTIM_OUT0_CFG,
    PINMUX_PAD30_UART2_TRX_CFG          = PINMUX_UART2_TRX_CFG,
    PINMUX_PAD30_UART1_TRX_CFG          = PINMUX_UART1_TRX_CFG,
    PINMUX_PAD30_SPI1_CS_CFG            = PINMUX_SPI1_CS_CFG,
    PINMUX_PAD30_I2C1_SCK_CFG           = PINMUX_I2C1_SCK_CFG,
    PINMUX_PAD30_RGB_OUT_CFG            = PINMUX_RGB_OUT_CFG,
    PINMUX_PAD30_I2S_SCLK_CFG           = PINMUX_I2S_SCLK_CFG,
    PINMUX_PAD30_TX_EXT_PD_CFG          = PINMUX_TX_EXT_PD_CFG,
    PINMUX_PAD30_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD30_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_30_func_t;

/// pin 31 pinmux function type
typedef enum {
    PINMUX_PAD31_TIM0_IO3_CFG           = PINMUX_TIM0_IO3_CFG,
    PINMUX_PAD31_TIM1_OUTN2_CFG         = PINMUX_TIM1_OUTN2_CFG,
    PINMUX_PAD31_TIM2_BKIN_CFG          = PINMUX_TIM2_BKIN_CFG,
    PINMUX_PAD31_LPTIM_OUT1_CFG         = PINMUX_LPTIM_OUT1_CFG,
    PINMUX_PAD31_UART2_RX_CFG           = PINMUX_UART2_RX_CFG,
    PINMUX_PAD31_UART1_CTS_CFG          = PINMUX_UART1_CTS_CFG,
    PINMUX_PAD31_SPI1_SCK_CFG           = PINMUX_SPI1_SCK_CFG,
    PINMUX_PAD31_I2C1_SDA_CFG           = PINMUX_I2C1_SDA_CFG,
    PINMUX_PAD31_IRTX_OUT_CFG           = PINMUX_IRTX_OUT_CFG,
    PINMUX_PAD31_AUDIO_EXT_CLK_CFG      = PINMUX_AUDIO_EXT_CLK_CFG,
    PINMUX_PAD31_RX_EXT_PD_CFG          = PINMUX_RX_EXT_PD_CFG,
    PINMUX_PAD31_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD31_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_31_func_t;

/// pin 32 pinmux function type
typedef enum {
    PINMUX_PAD32_TIM2_OUT0_CFG          = PINMUX_TIM2_OUT0_CFG,
    PINMUX_PAD32_TIM0_BKIN_CFG          = PINMUX_TIM0_BKIN_CFG,
    PINMUX_PAD32_LPTIM_OUT2_CFG         = PINMUX_LPTIM_OUT2_CFG,
    PINMUX_PAD32_UART0_TRX_CFG          = PINMUX_UART0_TRX_CFG,
    PINMUX_PAD32_UART1_RTS_CFG          = PINMUX_UART1_RTS_CFG,
    PINMUX_PAD32_SPI0_DI_CFG            = PINMUX_SPI0_DI_CFG,
    PINMUX_PAD32_I2C0_SCK_CFG           = PINMUX_I2C0_SCK_CFG,
    PINMUX_PAD32_QDEC_XA_CFG            = PINMUX_QDEC_XA_CFG,
    PINMUX_PAD32_I2S_SDI_CFG            = PINMUX_I2S_SDI_CFG,
    PINMUX_PAD32_PTA_ACTIVE_IN_CFG      = PINMUX_PTA_ACTIVE_IN_CFG,
    PINMUX_PAD32_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD32_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_32_func_t;

/// pin 33 pinmux function type
typedef enum {
    PINMUX_PAD33_TIM2_OUT1_CFG          = PINMUX_TIM2_OUT1_CFG,
    PINMUX_PAD33_TIM0_OUTN0_CFG         = PINMUX_TIM0_OUTN0_CFG,
    PINMUX_PAD33_TIM1_BKIN_CFG          = PINMUX_TIM1_BKIN_CFG,
    PINMUX_PAD33_LPTIM_OUT3_CFG         = PINMUX_LPTIM_OUT3_CFG,
    PINMUX_PAD33_UART0_RX_CFG           = PINMUX_UART0_RX_CFG,
    PINMUX_PAD33_UART1_RX_CFG           = PINMUX_UART1_RX_CFG,
    PINMUX_PAD33_SPI0_DIO_CFG           = PINMUX_SPI0_DIO_CFG,
    PINMUX_PAD33_I2C0_SDA_CFG           = PINMUX_I2C0_SDA_CFG,
    PINMUX_PAD33_QDEC_XB_CFG            = PINMUX_QDEC_XB_CFG,
    PINMUX_PAD33_I2S_SDO_CFG            = PINMUX_I2S_SDO_CFG,
    PINMUX_PAD33_PTA_ACTIVE_OUT_CFG     = PINMUX_PTA_ACTIVE_OUT_CFG,
    PINMUX_PAD33_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD33_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_33_func_t;

/// pin 34 pinmux function type
typedef enum {
    PINMUX_PAD34_TIM2_OUT2_CFG          = PINMUX_TIM2_OUT2_CFG,
    PINMUX_PAD34_TIM0_OUTN1_CFG         = PINMUX_TIM0_OUTN1_CFG,
    PINMUX_PAD34_TIM1_ETR_CFG           = PINMUX_TIM1_ETR_CFG,
    PINMUX_PAD34_DMIC_IN_CFG            = PINMUX_DMIC_IN_CFG,
    PINMUX_PAD34_UART2_TRX_CFG          = PINMUX_UART2_TRX_CFG,
    PINMUX_PAD34_UART1_TRX_CFG          = PINMUX_UART1_TRX_CFG,
    PINMUX_PAD34_SPI0_CS_CFG            = PINMUX_SPI0_CS_CFG,
    PINMUX_PAD34_I2C1_SCK_CFG           = PINMUX_I2C1_SCK_CFG,
    PINMUX_PAD34_QDEC_LED_CFG           = PINMUX_QDEC_LED_CFG,
    PINMUX_PAD34_I2S_WS_CFG             = PINMUX_I2S_WS_CFG,
    PINMUX_PAD34_PTA_PRIORITY_CFG       = PINMUX_PTA_PRIORITY_CFG,
    PINMUX_PAD34_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD34_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_34_func_t;

/// pin 35 pinmux function type
typedef enum {
    PINMUX_PAD35_TIM2_OUT3_CFG          = PINMUX_TIM2_OUT3_CFG,
    PINMUX_PAD35_TIM0_OUTN2_CFG         = PINMUX_TIM0_OUTN2_CFG,
    PINMUX_PAD35_TIM1_BKIN_CFG          = PINMUX_TIM1_BKIN_CFG,
    PINMUX_PAD35_DMIC_CLK_CFG           = PINMUX_DMIC_CLK_CFG,
    PINMUX_PAD35_UART2_RX_CFG           = PINMUX_UART2_RX_CFG,
    PINMUX_PAD35_UART1_CTS_CFG          = PINMUX_UART1_CTS_CFG,
    PINMUX_PAD35_SPI0_SCK_CFG           = PINMUX_SPI0_SCK_CFG,
    PINMUX_PAD35_I2C1_SDA_CFG           = PINMUX_I2C1_SDA_CFG,
    PINMUX_PAD35_QDEC_XA_CFG            = PINMUX_QDEC_XA_CFG,
    PINMUX_PAD35_I2S_SCLK_CFG           = PINMUX_I2S_SCLK_CFG,
    PINMUX_PAD35_PTA_FREQ_CFG           = PINMUX_PTA_FREQ_CFG,
    PINMUX_PAD35_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD35_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_35_func_t;

/// pin 36 pinmux function type
typedef enum {
    PINMUX_PAD36_TIM1_OUT0_CFG          = PINMUX_TIM1_OUT0_CFG,
    PINMUX_PAD36_LPTIM_OUT0_CFG         = PINMUX_LPTIM_OUT0_CFG,
    PINMUX_PAD36_UART2_TRX_CFG          = PINMUX_UART2_TRX_CFG,
    PINMUX_PAD36_UART1_RTS_CFG          = PINMUX_UART1_RTS_CFG,
    PINMUX_PAD36_I2C0_SCK_CFG           = PINMUX_I2C0_SCK_CFG,
    PINMUX_PAD36_QDEC_XB_CFG            = PINMUX_QDEC_XB_CFG,
    PINMUX_PAD36_AUDIO_EXT_CLK_CFG      = PINMUX_AUDIO_EXT_CLK_CFG,
    PINMUX_PAD36_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD36_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_36_func_t;

/// pin 37 pinmux function type
typedef enum {
    PINMUX_PAD37_TIM1_OUT1_CFG          = PINMUX_TIM1_OUT1_CFG,
    PINMUX_PAD37_LPTIM_OUT1_CFG         = PINMUX_LPTIM_OUT1_CFG,
    PINMUX_PAD37_UART2_RX_CFG           = PINMUX_UART2_RX_CFG,
    PINMUX_PAD37_UART1_RX_CFG           = PINMUX_UART1_RX_CFG,
    PINMUX_PAD37_I2C0_SDA_CFG           = PINMUX_I2C0_SDA_CFG,
    PINMUX_PAD37_QDEC_LED_CFG           = PINMUX_QDEC_LED_CFG,
    PINMUX_PAD37_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD37_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_37_func_t;

/// pin 38 pinmux function type
typedef enum {
    PINMUX_PAD38_LPTIM_OUT2_CFG         = PINMUX_LPTIM_OUT2_CFG,
    PINMUX_PAD38_UART1_TRX_CFG          = PINMUX_UART1_TRX_CFG,
    PINMUX_PAD38_IRTX_OUT_CFG           = PINMUX_IRTX_OUT_CFG,
    PINMUX_PAD38_INPUT_MODE_CFG         = PINMUX_INPUT_MODE_CFG,
    PINMUX_PAD38_GPIO_MODE_CFG          = PINMUX_GPIO_MODE_CFG,
} pin_38_func_t;

/// Pinmux Function
typedef union {
    uint8_t         pin_func;
    pin_0_func_t    pin0_func;
    pin_1_func_t    pin1_func;
    pin_2_func_t    pin2_func;
    pin_3_func_t    pin3_func;
    pin_4_func_t    pin4_func;
    pin_5_func_t    pin5_func;
    pin_6_func_t    pin6_func;
    pin_7_func_t    pin7_func;
    pin_8_func_t    pin8_func;
    pin_9_func_t    pin9_func;
    pin_10_func_t   pin10_func;
    pin_11_func_t   pin11_func;
    pin_12_func_t   pin12_func;
    pin_13_func_t   pin13_func;
    pin_14_func_t   pin14_func;
    pin_15_func_t   pin15_func;
    pin_16_func_t   pin16_func;
    pin_17_func_t   pin17_func;
    pin_18_func_t   pin18_func;
    pin_19_func_t   pin19_func;
    pin_20_func_t   pin20_func;
    pin_21_func_t   pin21_func;
    pin_22_func_t   pin22_func;
    pin_23_func_t   pin23_func;
    pin_24_func_t   pin24_func;
    pin_25_func_t   pin25_func;
    pin_26_func_t   pin26_func;
    pin_27_func_t   pin27_func;
    pin_28_func_t   pin28_func;
    pin_29_func_t   pin29_func;
    pin_30_func_t   pin30_func;
    pin_31_func_t   pin31_func;
    pin_32_func_t   pin32_func;
    pin_33_func_t   pin33_func;
    pin_34_func_t   pin34_func;
    pin_35_func_t   pin35_func;
    pin_36_func_t   pin36_func;
    pin_37_func_t   pin37_func;
    pin_38_func_t   pin38_func;
} pin_func_t;

/// Pin Configuration
typedef struct {
    uint8_t                      dig_pad;        /**< pin index */
    pin_func_t                   func;           /**< pad function */
    pmu_pin_mode_t               mode;           /**< pad mode */
    pmu_pin_driver_current_t     drv;            /**< driver current */
    pmu_pin_pullup_t             pullup;         /**< pullup */
} pin_config_t;


/*******************************************************************************
 * EXTERN FUNCTIONS
 */
/**
 *******************************************************************************
 * @brief Initialize pin function
 *
 * @param[in] pin      pin
 * @param[in] pinmux   pinmux function, @ref pinmux_t
 *
 *******************************************************************************
 */
extern void drv_pinmux_set(uint8_t pin, pinmux_t pinmux);

/**
 *******************************************************************************
 * @brief get pinmux configuration type
 *
 * @param[in] pin      Configuration number for pinmux
 *
 *******************************************************************************
 */
extern pinmux_t drv_pinmux_get(uint8_t pin);

/**
 *******************************************************************************
 * @brief Initialize pin function and electrical characteristics
 *
 * @param[in] pin_cfg           Configuration for pinmux
 * @param[in] pin_cfg_num       Configuration number for pinmux
 *
 *******************************************************************************
 */
extern void drv_pin_init(const pin_config_t *pin_cfg, uint32_t pin_cfg_num);


#ifdef __cplusplus
}
#endif

#endif  /* RTE_PIN */
#endif  /* __DRV_PIN_H */


/** @} */
