/* ----------------------------------------------------------------------------
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 * -------------------------------------------------------------------------- */

/**
 * @defgroup DOC DOC
 * @ingroup  DOCUMENT
 * @brief    EVB board pin define
 * @details  EVB board pin define
 *
 * @version
 * Version 1.0
 *  - Initial release
 *
 * @{
 */

/*******************************************************************************
 * INCLUDES
 */
#include "RTE_driver.h"
#include "om_driver.h"
#include "board_define.h"


/*******************************************************************************
 * MACROS
 */
/* see @pmu_32k_sel_t, selection in RC32K/XTAL32K/DIV from XTAL32M */
#define BOARD_32K_SELECT            PMU_32K_SEL_RC


/*******************************************************************************
 * CONSTANTS
 */
static const pin_config_t pin_config[] = {
	
	{PAD_MICP, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_FLOAT, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_MICN, {PINMUX_GPIO_MODE_CFG},  PMU_PIN_MODE_FLOAT, PMU_PIN_DRIVER_CURRENT_NORMAL},
	
	
    #if (RTE_UART0)
    {PAD_UART0_TXD, {PINMUX_PAD5_UART0_TRX_CFG}, PMU_PIN_MODE_PU, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_UART0_RXD, {PINMUX_PAD6_UART0_RX_CFG},  PMU_PIN_MODE_PU, PMU_PIN_DRIVER_CURRENT_NORMAL},
    #endif

    #if (RTE_UART1)
    {PAD_UART1_TXD, {PINMUX_PAD22_UART1_TRX_CFG}, PMU_PIN_MODE_PU, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_UART1_RXD, {PINMUX_PAD21_UART1_RX_CFG},  PMU_PIN_MODE_PU, PMU_PIN_DRIVER_CURRENT_NORMAL},
    #endif

	#if (RTE_UART2)
    {PAD_UART2_TXD, {PINMUX_PAD18_UART2_TRX_CFG}, PMU_PIN_MODE_PU, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_UART2_RXD, {PINMUX_PAD19_UART2_RX_CFG},  PMU_PIN_MODE_PU, PMU_PIN_DRIVER_CURRENT_NORMAL},
    #endif
	
    #if (defined(PAD_RF_TXEN) && defined(PAD_RF_RXEN))
    {PAD_RF_RXEN, {PINMUX_PAD13_RX_EXT_PD_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_RF_TXEN, {PINMUX_PAD12_TX_EXT_PD_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    #endif
    //charge check
    {PAD_CHAGE_CHECK, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_FLOAT, PMU_PIN_DRIVER_CURRENT_NORMAL},
	
    #if (defined(PAD_USBD_DM) && defined(PAD_USBD_DP))
    {PAD_USBD_DM, {PINMUX_PAD16_USB_DM_CFG}, PMU_PIN_MODE_PD, PMU_PIN_DRIVER_CURRENT_MAX},
    {PAD_USBD_DP, {PINMUX_PAD17_USB_DP_CFG}, PMU_PIN_MODE_PD, PMU_PIN_DRIVER_CURRENT_MAX},
    #endif
    //low power control     
    {PAD_CONTROL_LOW_POWER, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    //GPADC
    {PAD_GPADC_CH_GPIO14, {MUX_GPADC_CH_GPIO14}, PMU_PIN_MODE_FLOAT, PMU_PIN_DRIVER_CURRENT_NORMAL},
    //MOTOR
    {PAD_MOTOR_PAD_GPIO, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    //EXFLASH
    {PAD_OSPI1_CS, {PINMUX_PAD8_OSPI1_CS_CFG},  PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_OSPI1_CK, {PINMUX_PAD9_OSPI1_CK_CFG},  PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_OSPI1_SI, {PINMUX_PAD10_OSPI1_SI_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_OSPI1_SO, {PINMUX_PAD7_OSPI1_SO_CFG},  PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_OSPI1_WP, {PINMUX_PAD12_OSPI1_WP_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_OSPI1_HD, {PINMUX_PAD11_OSPI1_HD_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
	
    {PAD_CAT1_DTR, 			{PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_CAT1_RING, 		{PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PU, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_CAT1_POWERKEY, 	{PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL}, //PMU_PIN_MODE_FLOAT
    {PAD_CAT1_POWER, 		{PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
	
	{PAD_GNSS_POWER, 		{PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_GNSS_BACKUPPOWER, 	{PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_GNSS_WAKEUP, 		{PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL}, //PMU_PIN_MODE_FLOAT
    {PAD_GNSS_REST, 		{PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_FLOAT, PMU_PIN_DRIVER_CURRENT_NORMAL},
	//修改于20251223适配最新GNSS硬件设计的LDO控制
//    {PAD_GNSS_REST, 		{PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PD, PMU_PIN_DRIVER_CURRENT_NORMAL},
	//LED PAD 
	{LED_SCL_IO,			{LED_SCL_IO_MUX}, PMU_PIN_MODE_OD, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {LED_SDA_IO, 			{LED_SDA_IO_MUX}, PMU_PIN_MODE_OD, PMU_PIN_DRIVER_CURRENT_NORMAL},

		//sensor
    {SPI_CS,  				{MUX_SPI_CS},  	 PMU_PIN_MODE_PU, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {SPI_SCK, 				{MUX_SPI_SCK}, 	 PMU_PIN_MODE_PU, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {SPI_MOSI,  			{MUX_SPI_MOSI},  PMU_PIN_MODE_PU, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {SPI_MISO, 				{MUX_SPI_MISO},	 PMU_PIN_MODE_PU, PMU_PIN_DRIVER_CURRENT_NORMAL},
	{IMU_INT1,  			{PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PU, PMU_PIN_DRIVER_CURRENT_NORMAL},
	//audio
	{AUDIO_SD_IO,			{PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
	
	{AUDIO_PLAY_IO, 		{AUDIO_PLAY_IO_MUX_CH0}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_MAX},
	
};

static const gpio_config_t gpio_config[] = {
	{OM_GPIO0, PAD_MICP, 	 GPIO_DIR_INPUT,  GPIO_LEVEL_HIGH, GPIO_TRIG_NONE},
	{OM_GPIO0, PAD_MICN, 	 GPIO_DIR_INPUT,  GPIO_LEVEL_HIGH, GPIO_TRIG_NONE},
    //charge check
    {OM_GPIO0, PAD_CHAGE_CHECK, 	 GPIO_DIR_INPUT,  GPIO_LEVEL_LOW, GPIO_TRIG_RISING_FAILING_EDGE}, 
//MOTOR
    {OM_GPIO0, PAD_MOTOR_PAD_GPIO,  GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
//low power set low on
    {OM_GPIO0, PAD_CONTROL_LOW_POWER,  GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},

    {OM_GPIO0, PAD_CAT1_DTR,   GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE}, //Low to wakeup CAT1; High allow CAT1 to sleep
    {OM_GPIO0, PAD_CAT1_RING,  GPIO_DIR_INPUT,  GPIO_LEVEL_HIGH, GPIO_TRIG_FALLING_EDGE},//falling edge trigger, need check in ISR
    {OM_GPIO1, PAD_CAT1_POWERKEY, 	GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
    {OM_GPIO0, PAD_CAT1_POWER, 		GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
	
	
	{OM_GPIO1, PAD_GNSS_POWER, 		GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},         // Low to wakeup CAT1; High allow CAT1 to sleep
    {OM_GPIO0, PAD_GNSS_BACKUPPOWER, GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE}, // falling edge trigger, need check in ISR
    {OM_GPIO0, PAD_GNSS_WAKEUP, 	GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
   // {OM_GPIO0, PAD_GNSS_REST, 		GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
	{OM_GPIO0, PAD_GNSS_REST, 		GPIO_DIR_INPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
	//sensor INT1
	{OM_GPIO0, IMU_INT1, GPIO_DIR_INPUT,  GPIO_LEVEL_HIGH,	GPIO_TRIG_FALLING_EDGE},
	
	{OM_GPIO0, AUDIO_SD_IO,		GPIO_DIR_OUTPUT, GPIO_LEVEL_HIGH, GPIO_TRIG_NONE}, // PWM输出控制脚
};


/*******************************************************************************
 * PUBLIC FUNCTIONS
 */
void board_init(void)
{
    // Use DCDC
    drv_pmu_dcdc_enable(true);

    /* Change xtal 32m params & startup */
    drv_pmu_xtal32m_change_param(34);//宠物项实际测试
    drv_pmu_xtal32m_startup();
	
	drv_pmu_syspll_power_enable(true);
//	drv_rcc_cpu_clk_source_set(RCC_CPU_CLK_SOURCE_SYSPLL96M);
    // periph clock switch to 64M
//drv_rcc_periph_clk_source_set(RCC_PERIPH_CLK_SOURCE_XTAL64M);
	/* Change xtal 32k params & select 32K source */
    // drv_pmu_xtal32k_change_param(load_capacitance, drive_current);
    drv_pmu_select_32k(PMU_32K_SEL_RC);

    drv_pin_init(pin_config, sizeof(pin_config) / sizeof(pin_config[0]));
    drv_gpio_init(gpio_config, sizeof(gpio_config) / sizeof(gpio_config[0]));
}



static const pin_config_t pin_config_deinit[] = {

    //GPADC
    {PAD_GPADC_CH_GPIO14, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_FLOAT, PMU_PIN_DRIVER_CURRENT_NORMAL},
    //MOTOR
    {PAD_MOTOR_PAD_GPIO, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    
	 // mic
    {PAD_MICP, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_MICN, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
	//EXFLASH
//	{PAD_OSPI1_CS, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_FLOAT, PMU_PIN_DRIVER_CURRENT_NORMAL},
//    {PAD_OSPI1_CK, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_FLOAT, PMU_PIN_DRIVER_CURRENT_NORMAL},
//    {PAD_OSPI1_SI, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_FLOAT, PMU_PIN_DRIVER_CURRENT_NORMAL},
//    {PAD_OSPI1_SO, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_FLOAT, PMU_PIN_DRIVER_CURRENT_NORMAL},
//    {PAD_OSPI1_WP, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_FLOAT, PMU_PIN_DRIVER_CURRENT_NORMAL},
//    {PAD_OSPI1_HD, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_FLOAT, PMU_PIN_DRIVER_CURRENT_NORMAL},
     // wake up
    {PAD_CHAGE_CHECK, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_FLOAT, PMU_PIN_DRIVER_CURRENT_NORMAL},
	// USB
    {PAD_USBD_DM, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_USBD_DP, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
	//LED PAD 
	{LED_SCL_IO, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_FLOAT, PMU_PIN_DRIVER_CURRENT_NORMAL},
	{LED_SDA_IO, {PINMUX_GPIO_MODE_CFG}, PMU_PIN_MODE_FLOAT, PMU_PIN_DRIVER_CURRENT_NORMAL},
	//sensor
    {SPI_CS,  				{PINMUX_GPIO_MODE_CFG},  	PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {SPI_SCK, 				{PINMUX_GPIO_MODE_CFG}, 	PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {SPI_MOSI,  			{PINMUX_GPIO_MODE_CFG},		PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {SPI_MISO, 				{PINMUX_GPIO_MODE_CFG},	 	PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
	{IMU_INT1,  			{PINMUX_GPIO_MODE_CFG}, 	PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
	//audio
	{AUDIO_SD_IO,			{PINMUX_GPIO_MODE_CFG}, 	PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
	{AUDIO_PLAY_IO, 		{PINMUX_GPIO_MODE_CFG}, 	PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_MAX},
	//GNSS
	{PAD_GNSS_WAKEUP, 		{PINMUX_GPIO_MODE_CFG}, 	PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_GNSS_REST, 		{PINMUX_GPIO_MODE_CFG}, 	PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_UART2_TXD, 		{PINMUX_GPIO_MODE_CFG},	 	PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL}, //PMU_PIN_MODE_FLOAT
    {PAD_UART2_RXD, 		{PINMUX_GPIO_MODE_CFG}, 	PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
	    // LTE
    {PAD_CAT1_POWERKEY, {PINMUX_GPIO_MODE_CFG},		 PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_CAT1_RING, 	{PINMUX_GPIO_MODE_CFG}, 	 PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    { PAD_CAT1_DTR, 	{PINMUX_GPIO_MODE_CFG}, 	 PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_UART1_RXD, 	{PINMUX_GPIO_MODE_CFG}, 	 PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_UART1_TXD, 	{PINMUX_GPIO_MODE_CFG}, 	 PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},


    {PAD_GNSS_POWER, 		{PINMUX_GPIO_MODE_CFG}, 		PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_CONTROL_LOW_POWER, {PINMUX_GPIO_MODE_CFG}, 		PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_GNSS_BACKUPPOWER, 	{PINMUX_GPIO_MODE_CFG}, 		PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
    {PAD_CAT1_POWER, 		{PINMUX_GPIO_MODE_CFG},			PMU_PIN_MODE_PP, PMU_PIN_DRIVER_CURRENT_NORMAL},
};
static const gpio_config_t gpio_config_deinit[] = {
	
	  // motor
    {OM_GPIO0, PAD_MOTOR_PAD_GPIO, GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
   // mic
    {OM_GPIO0, PAD_MICP, GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
    {OM_GPIO0, PAD_MICN, GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},

//	   // Flash
//    {OM_GPIO0, PAD_OSPI1_CS, GPIO_DIR_INPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
//    {OM_GPIO0, PAD_OSPI1_CK, GPIO_DIR_INPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
//    {OM_GPIO0, PAD_OSPI1_SI, GPIO_DIR_INPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
//    {OM_GPIO0, PAD_OSPI1_SO, GPIO_DIR_INPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
//    {OM_GPIO0, PAD_OSPI1_WP, GPIO_DIR_INPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
//    {OM_GPIO0, PAD_OSPI1_HD, GPIO_DIR_INPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},

	   // USB
    {OM_GPIO0, PAD_USBD_DM,    GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
    {OM_GPIO0, PAD_USBD_DP,    GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},

	    // 六轴
    {OM_GPIO1, SPI_CS, 		GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
    {OM_GPIO1, SPI_SCK, 	GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
    {OM_GPIO1, SPI_MOSI, 	GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
    {OM_GPIO1, SPI_MISO, 	GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
    {OM_GPIO0, IMU_INT1, 	GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
	
	    // 充电检测
    {OM_GPIO0, PAD_CHAGE_CHECK, GPIO_DIR_INPUT,  GPIO_LEVEL_LOW, GPIO_TRIG_RISING_FAILING_EDGE},
	   // LED
    {OM_GPIO0, LED_SCL_IO,    GPIO_DIR_INPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
    {OM_GPIO0, LED_SDA_IO,    GPIO_DIR_INPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},

//	  // 喇叭
    {OM_GPIO0, AUDIO_SD_IO, 		GPIO_DIR_OUTPUT, GPIO_LEVEL_HIGH, GPIO_TRIG_NONE},
	{OM_GPIO0, AUDIO_PLAY_IO,		GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE}, // PWM输出控制脚
 
 //GPADC
	{OM_GPIO0, PAD_GPADC_CH_GPIO14,  GPIO_DIR_INPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
	
	    // GNSS
    {OM_GPIO0, PAD_GNSS_WAKEUP, GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
    {OM_GPIO0, PAD_GNSS_REST, 	GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
    {OM_GPIO0, PAD_UART2_TXD, 	GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
    {OM_GPIO0, PAD_UART2_RXD, 	GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
    
    // LTE
    {OM_GPIO1, PAD_CAT1_POWERKEY, 	GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
    {OM_GPIO0, PAD_CAT1_RING, 		GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
    {OM_GPIO0, PAD_CAT1_DTR, 		GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
    {OM_GPIO0, PAD_UART1_RXD, 		GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
    {OM_GPIO0, PAD_UART1_TXD, 		GPIO_DIR_OUTPUT, GPIO_LEVEL_LOW, GPIO_TRIG_NONE},
	

    {OM_GPIO1, PAD_GNSS_POWER, 			GPIO_DIR_OUTPUT, GPIO_LEVEL_HIGH, GPIO_TRIG_NONE},
    {OM_GPIO0, PAD_CONTROL_LOW_POWER, 	GPIO_DIR_OUTPUT, GPIO_LEVEL_HIGH, GPIO_TRIG_NONE},
    {OM_GPIO0, PAD_GNSS_BACKUPPOWER, 	GPIO_DIR_OUTPUT, GPIO_LEVEL_HIGH, GPIO_TRIG_NONE},
    {OM_GPIO0, PAD_CAT1_POWER, 			GPIO_DIR_OUTPUT, GPIO_LEVEL_HIGH, GPIO_TRIG_NONE},
				//sensor	

};


void board_deinit(void)
{
	drv_pin_init(pin_config_deinit, sizeof(pin_config_deinit) / sizeof(pin_config_deinit[0]));
	drv_gpio_init(gpio_config_deinit, sizeof(gpio_config_deinit) / sizeof(gpio_config_deinit[0]));
}


/** @} */
